project:
  type: website
  output-dir: _site

website:
  title: "Statistical Computing"
  navbar:
    background: light
    search: true
    right:
      - index.qmd
      - Prac1.qmd
      - Day3.qmd
      - Prac4.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
